version: "3.7"
services:

  flag-submitter:
    image: registry.fuo.ninja/fuomag9/actually-good-flag-submitter:latest
    volumes:
      - "./config.conf:/flag_submitter/config.conf"
      - "./teamsips.txt:/flag_submitter/teamsips.txt"
      - "./exploits/:/flag_submitter/exploits/"
      - "./proto/:/flag_submitter/proto"
